<script setup lang="ts">
import { ArrowLeftRight, Banknote, Bell, Check, CircleAlert, CircleCheck, CircleX, CreditCard, Info, LoaderCircle, Minus, Package, Plus, Search, ShoppingCart, Tags, Trash2, UserRound, X } from '@lucide/vue'
</script>
<template>
  <section class="fade-up library-page">
    <div class="page-heading"><div><p class="eyebrow">Sistema visual</p><h1>Biblioteca de componentes</h1><p>Controles compartidos de MercaPOS.</p></div></div>
    <section class="panel library-section"><div class="panel-header"><div><h2>Botones</h2><p>Acciones principales, secundarias e iconos.</p></div></div><div class="library-content">
      <div class="library-row"><button class="btn">Primary</button><button class="btn btn-secondary">Secondary</button><button class="btn btn-success"><Check :size="15"/> Success</button><button class="btn btn-danger"><Trash2 :size="15"/> Danger</button><button class="btn btn-outline">Outline</button><button class="icon-button" aria-label="Buscar"><Search :size="16"/></button><button class="btn" disabled>Disabled</button><button class="btn" disabled><LoaderCircle class="spin-icon" :size="15"/> Loading</button></div>
      <div class="state-caption">Normal · Hover · Focus · Disabled · Loading · Success</div>
    </div></section>
    <section class="panel library-section"><div class="panel-header"><div><h2>Campos</h2><p>Entradas simples y selección.</p></div></div><div class="library-content library-form-grid">
      <label class="form-field">Texto<input class="field" placeholder="Nombre del producto" /></label><label class="form-field">Búsqueda<div class="library-search"><Search :size="15"/><input placeholder="Buscar productos" /></div></label><label class="form-field">Contraseña<div class="library-search"><input type="password" value="password123"/><button class="table-action" aria-label="Mostrar contraseña"><Info :size="15"/></button></div></label><label class="form-field">Selección<select class="field"><option>Selecciona una opción</option><option>Opción de ejemplo</option></select></label><label class="form-field">Fecha<input class="field" type="date" /></label><label class="form-field">Estado de campo<input class="field field-error" value="Código duplicado"/><small class="field-error-text">Este valor ya existe.</small></label>
      <label class="library-check"><input type="checkbox" checked/> Checkbox</label><label class="library-check"><input type="radio" name="sample-radio" checked/> Radio button</label><label class="library-check"><input class="library-switch" type="checkbox" role="switch" checked/> Switch</label>
    </div></section>
    <section class="panel library-section"><div class="panel-header"><div><h2>Componentes POS</h2><p>Tarjetas, cantidades, tabla y pago.</p></div></div><div class="library-content pos-library-grid">
      <article class="sale-product-card library-product"><span class="sale-product-visual"><Package :size="24"/><span class="product-stock">Stock 12</span></span><span class="sale-product-name">Café molido 500 g</span><span class="sale-product-meta">CAF-0500</span><span class="sale-product-bottom"><strong>L 125.00</strong><span class="add-product-button"><Plus :size="15"/></span></span></article>
      <article class="category-sample"><span class="category-sample-icon"><Tags :size="18"/></span><strong>Abarrotes</strong><small>24 productos</small></article>
      <article class="library-cart-item"><div class="cart-item-thumb"><Package :size="17"/></div><div><strong>Leche entera 1 L</strong><small>L 34.00 c/u</small><div class="quantity-stepper"><button><Minus :size="12"/></button><span>2</span><button><Plus :size="12"/></button></div></div><button class="table-action delete"><X :size="14"/></button></article>
      <div class="library-payment-methods"><button class="payment-method active"><Banknote :size="18"/><span>Efectivo</span><i></i></button><button class="payment-method"><CreditCard :size="18"/><span>Tarjeta</span><i></i></button><button class="payment-method"><ArrowLeftRight :size="18"/><span>Transferencia</span><i></i></button></div>
      <div class="library-user-row"><span class="user-avatar"><UserRound :size="16"/></span><span><strong>María López</strong><small>Vendedora</small></span><span class="status-pill">Activo</span></div>
      <div class="library-table-sample"><table class="data-table"><thead><tr><th>Producto</th><th>Stock</th><th>Precio</th></tr></thead><tbody><tr><td class="row-primary">Agua 1 L</td><td>18</td><td>L 22.00</td></tr></tbody></table></div>
    </div></section>
    <section class="panel library-section"><div class="panel-header"><div><h2>Mensajes y estados</h2><p>Feedback visible y directo.</p></div></div><div class="library-content feedback-grid">
      <div class="feedback-sample feedback-success"><CircleCheck :size="17"/><span><strong>Venta guardada</strong><small>La operación terminó correctamente.</small></span></div><div class="feedback-sample feedback-warning"><CircleAlert :size="17"/><span><strong>Stock bajo</strong><small>Quedan pocas unidades disponibles.</small></span></div><div class="feedback-sample feedback-error"><CircleX :size="17"/><span><strong>No se pudo guardar</strong><small>Revisa los datos e inténtalo de nuevo.</small></span></div><div class="feedback-sample feedback-info"><Info :size="17"/><span><strong>Turno activo</strong><small>La caja está lista para vender.</small></span></div>
      <div class="toast-sample"><Bell :size="15"/><span>Producto agregado al carrito</span><button aria-label="Cerrar"><X :size="14"/></button></div><div class="loading-sample"><LoaderCircle class="spin-icon" :size="18"/><span>Cargando lista…</span></div><div class="mini-dialog"><div class="mini-dialog-icon"><ShoppingCart :size="18"/></div><strong>¿Vaciar el carrito?</strong><small>Se quitarán todos los productos agregados.</small><div><button class="btn btn-secondary">Cancelar</button><button class="btn btn-danger">Vaciar</button></div></div><div class="library-empty"><ShoppingCart :size="22"/><strong>Carrito vacío</strong><small>Los productos agregados aparecerán aquí.</small></div>
    </div></section>
  </section>
</template>
+